sudo: required
#language: generic
services:
    - docker

before_install:
    - docker build -t abeljm/udemy-docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true abeljm/udemy-docker-react npm run test